### ISSUE TITLE
Failed to build module 'QuickPaySDK' from its module

### ISSUE THREAD

**Issue by govindagile** [QuickPay/ios-sdk-pod#1]
Failed to build module 'QuickPaySDK' from its module interface; the compiler that produced it, 'Apple Swift version 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)'

**Comment by Steffen84** [comment]
Hi govindagile.

We have just migrated our SDK into a swift package rather than using CocoaPods. So this repo is no longer maintained.

Please add this repo as a swift package into your project https://github.com/QuickPay/ios-sdk
