### ISSUE TITLE
QuickPay Framework forældet

### ISSUE THREAD

**Issue by ghost** [QuickPay/ios-sdk-pod#2]
Kære QuickPay,
jeres .framework er forældet og virker ikke længere med Xcode 12, hvis i kunne opdaterer det til .xcframework ville det være fantastisk! Fejlen viser sig når man downloader jeres starterprojekt og compiler :)
Mvh Johan

**Comment by Steffen84** [comment]
Hej Johan.
Tak for din besked.

Vi er gået væk fra at distribuere frameworket via CocoaPods og anvender i stedet swift packages, så dette repo vedligeholdes ikke.

Du kan tilgå det opdaterede repo som understøtter swift packages her https://github.com/QuickPay/ios-sdk
