### ISSUE TITLE
QuickPay framework outdated

### ISSUE THREAD

**Issue by ghost** [QuickPay/ios-sdk-pod#3]
Your Example Project fails at compiling. This is caused by the outdated .framework used in the project. Please consider updating the framework to a .xcframework or find another solution. It's quite frustrating :)
Kind Regards!

**Comment by Steffen84** [comment]
Hi Loofers.

We have just migrated our SDK into a swift package rather than using CocoaPods. So this repo is no longer maintained.

Please add this repo as a swift package into your project https://github.com/QuickPay/ios-sdk
